-- MySQL Script generated by MySQL Workbench
-- Ter 08 Dez 2020 16:39:51 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema simplestore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simplestore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simplestore` DEFAULT CHARACTER SET utf8 ;
USE `simplestore` ;

-- -----------------------------------------------------
-- Table `simplestore`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Roles` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Buy` TINYINT(1) NOT NULL,
  `Sale` TINYINT(1) NOT NULL,
  `Delivery` TINYINT(1) NOT NULL,
  `Receive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Address` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `State` VARCHAR(100) NOT NULL,
  `City` VARCHAR(100) NOT NULL,
  `District` VARCHAR(100) NOT NULL,
  `Street` VARCHAR(100) NOT NULL,
  `Number` VARCHAR(10) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Employees` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Telephone` VARCHAR(15) NULL,
  `Address` INT NULL,
  `Role` VARCHAR(100) NOT NULL,
  `idRoles` INT NOT NULL,
  PRIMARY KEY (`idEmployees`, `idRoles`),
  INDEX `Cargo_idx` (`idRoles` ASC),
  INDEX `Endereco_idx` (`Address` ASC),
  CONSTRAINT `idRoles`
    FOREIGN KEY (`idRoles`)
    REFERENCES `simplestore`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Address`
    FOREIGN KEY (`Address`)
    REFERENCES `simplestore`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Customers` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Telephone` VARCHAR(15) NULL,
  `Address` INT NULL,
  PRIMARY KEY (`idCustomers`),
  INDEX `Endereco_idx` (`Address` ASC),
  CONSTRAINT `CostumersAddress`
    FOREIGN KEY (`Address`)
    REFERENCES `simplestore`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Suppliers` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Suppliers` (
  `idSuppliers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Telephone` VARCHAR(15) NULL,
  `Address` INT NULL,
  PRIMARY KEY (`idSuppliers`),
  INDEX `Endereco_idx` (`Address` ASC),
  CONSTRAINT `AddressSuppliers`
    FOREIGN KEY (`Address`)
    REFERENCES `simplestore`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Products` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Supplier` VARCHAR(100) NOT NULL,
  `idSuppliers` INT NOT NULL,
  `Cost` DECIMAL NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`idProducts`, `idSuppliers`),
  INDEX `Fornecedor_idx` (`idSuppliers` ASC),
  CONSTRAINT `Suppliers`
    FOREIGN KEY (`idSuppliers`)
    REFERENCES `simplestore`.`Suppliers` (`idSuppliers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Services` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Services` (
  `idServices` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Cost` DECIMAL NOT NULL,
  `Price` DECIMAL NOT NULL,
  `Time` INT NULL,
  `Description` VARCHAR(500) NULL,
  PRIMARY KEY (`idServices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Receipts` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Receipts` (
  `idReceipts` INT NOT NULL AUTO_INCREMENT,
  `idSales` INT NOT NULL,
  `CodSales` INT NOT NULL,
  `Date_receipts` DATETIME NOT NULL,
  `Value` DECIMAL NOT NULL,
  PRIMARY KEY (`idReceipts`),
  INDEX `idVenda_idx` (`idSales` ASC),
  CONSTRAINT `idSales`
    FOREIGN KEY (`idSales`)
    REFERENCES `simplestore`.`Sales` (`idSales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Deliveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Deliveries` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Deliveries` (
  `idDeliveries` INT NOT NULL AUTO_INCREMENT,
  `idSales` INT NOT NULL,
  `CodSales` INT NOT NULL,
  `Date_delivery` DATETIME NOT NULL,
  `Address` INT NOT NULL,
  PRIMARY KEY (`idDeliveries`),
  INDEX `Endereco_idx` (`Address` ASC),
  INDEX `idVenda_idx` (`idSales` ASC),
  CONSTRAINT `idSalesDeliveries`
    FOREIGN KEY (`idSales`)
    REFERENCES `simplestore`.`Sales` (`idSales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DeliveriesAddress`
    FOREIGN KEY (`Address`)
    REFERENCES `simplestore`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Payments` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Payments` (
  `idPayments` INT NOT NULL AUTO_INCREMENT,
  `idPurchases` INT NOT NULL,
  `CodPurchase` INT NOT NULL,
  `Date_payment` DATETIME NOT NULL,
  `Value` DECIMAL NOT NULL,
  PRIMARY KEY (`idPayments`),
  INDEX `idCompra_idx` (`idPurchases` ASC),
  CONSTRAINT `idPurchases`
    FOREIGN KEY (`idPurchases`)
    REFERENCES `simplestore`.`Purchases` (`idPurchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Purchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Purchases` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Purchases` (
  `idPurchases` INT NOT NULL AUTO_INCREMENT,
  `CodPurchase` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Date_delivery` DATETIME NULL,
  `Employee` VARCHAR(100) NOT NULL,
  `idEmployees` INT NOT NULL,
  `Supplier` VARCHAR(100) NOT NULL,
  `idSuppliers` INT NOT NULL,
  `Product` VARCHAR(100) NOT NULL,
  `idProducts` INT NOT NULL,
  `Payment` DECIMAL NOT NULL,
  `idPayments` INT NOT NULL,
  `idAppointments` INT NULL,
  PRIMARY KEY (`idPurchases`, `idEmployees`, `idSuppliers`, `idProducts`, `idPayments`),
  INDEX `Apontamento_idx` (`idAppointments` ASC),
  INDEX `Pagamento_idx` (`idPayments` ASC),
  INDEX `Bem_idx` (`idProducts` ASC),
  INDEX `Fornecedor_idx` (`idSuppliers` ASC),
  INDEX `Funcionario_idx` (`idEmployees` ASC),
  CONSTRAINT `idEmployees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `simplestore`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSuppliers`
    FOREIGN KEY (`idSuppliers`)
    REFERENCES `simplestore`.`Suppliers` (`idSuppliers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProducts`
    FOREIGN KEY (`idProducts`)
    REFERENCES `simplestore`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPayments`
    FOREIGN KEY (`idPayments`)
    REFERENCES `simplestore`.`Payments` (`idPayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAppointments`
    FOREIGN KEY (`idAppointments`)
    REFERENCES `simplestore`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Activities` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Activities` (
  `idActivities` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NULL,
  PRIMARY KEY (`idActivities`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Agenda` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Time_begin` DATETIME NOT NULL,
  `Time_finish` DATETIME NOT NULL,
  `Activity` VARCHAR(100) NOT NULL,
  `idActivities` INT NOT NULL,
  `Employee` VARCHAR(100) NOT NULL,
  `idEmployees` INT NOT NULL,
  `idAppointments` INT NULL,
  PRIMARY KEY (`idAgenda`, `idActivities`, `idEmployees`),
  INDEX `idAtividade_idx` (`idActivities` ASC),
  INDEX `idFuncionario_idx` (`idEmployees` ASC),
  INDEX `idApontamento_idx` (`idAppointments` ASC),
  CONSTRAINT `idActivitiesAgenda`
    FOREIGN KEY (`idActivities`)
    REFERENCES `simplestore`.`Activities` (`idActivities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEmployeesAgenda`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `simplestore`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAppointmentsAgenda`
    FOREIGN KEY (`idAppointments`)
    REFERENCES `simplestore`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Appointments` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Appointments` (
  `idAppointments` INT NOT NULL AUTO_INCREMENT,
  `idSales` INT NULL,
  `idPurchases` INT NULL,
  `idAgenda` INT NULL,
  PRIMARY KEY (`idAppointments`),
  INDEX `fk_Apontamentos_1_idx` (`idSales` ASC),
  INDEX `idPurchases_idx` (`idPurchases` ASC),
  INDEX `idAgenda_idx` (`idAgenda` ASC),
  CONSTRAINT `idSalesAppointments`
    FOREIGN KEY (`idSales`)
    REFERENCES `simplestore`.`Sales` (`idSales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPurchasesAppointments`
    FOREIGN KEY (`idPurchases`)
    REFERENCES `simplestore`.`Purchases` (`idPurchases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAgenda`
    FOREIGN KEY (`idAgenda`)
    REFERENCES `simplestore`.`Agenda` (`idAgenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Sales` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Sales` (
  `idSales` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `CodSales` INT NOT NULL,
  `Employee` VARCHAR(100) NOT NULL,
  `idEmployees` INT NOT NULL,
  `Customer` VARCHAR(100) NOT NULL,
  `idCustomers` INT NOT NULL,
  `Product` VARCHAR(100) NULL,
  `idProducts` INT NULL,
  `Service` VARCHAR(100) NULL,
  `idServices` INT NULL,
  `Receipt` DECIMAL NOT NULL,
  `idReceipts` INT NOT NULL,
  `idDeliveries` INT NULL,
  `idAppointments` INT NULL,
  INDEX `Funcionario_idx` (`idEmployees` ASC),
  INDEX `Cliente_idx` (`idCustomers` ASC),
  INDEX `Bem_idx` (`idProducts` ASC),
  INDEX `Servico_idx` (`idServices` ASC),
  INDEX `Recebimento_idx` (`idReceipts` ASC),
  INDEX `Entrega_idx` (`idDeliveries` ASC),
  INDEX `Apontamento_idx` (`idAppointments` ASC),
  PRIMARY KEY (`idSales`, `idReceipts`, `idCustomers`, `idEmployees`),
  CONSTRAINT `idEmployeesSales`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `simplestore`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCustomersSales`
    FOREIGN KEY (`idCustomers`)
    REFERENCES `simplestore`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProductsSales`
    FOREIGN KEY (`idProducts`)
    REFERENCES `simplestore`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServicesSales`
    FOREIGN KEY (`idServices`)
    REFERENCES `simplestore`.`Services` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idReceiptsSales`
    FOREIGN KEY (`idReceipts`)
    REFERENCES `simplestore`.`Receipts` (`idReceipts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDeliveriesSales`
    FOREIGN KEY (`idDeliveries`)
    REFERENCES `simplestore`.`Deliveries` (`idDeliveries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAppointmentsSales`
    FOREIGN KEY (`idAppointments`)
    REFERENCES `simplestore`.`Appointments` (`idAppointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Inventories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Inventories` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Inventories` (
  `idInventories` INT NOT NULL AUTO_INCREMENT,
  `Product` VARCHAR(100) NOT NULL,
  `idProducts` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`idInventories`, `idProducts`),
  INDEX `Bem_idx` (`idProducts` ASC),
  CONSTRAINT `idProductsInventories`
    FOREIGN KEY (`idProducts`)
    REFERENCES `simplestore`.`Products` (`idProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Expenses` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Expenses` (
  `idExpenses` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Value` DECIMAL NOT NULL,
  PRIMARY KEY (`idExpenses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simplestore`.`Cash_register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simplestore`.`Cash_register` ;

CREATE TABLE IF NOT EXISTS `simplestore`.`Cash_register` (
  `idCash_register` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `Cash_value` DECIMAL NOT NULL,
  `Withdraw` DECIMAL NULL,
  `Deposit` DECIMAL NULL,
  `Expense` DECIMAL NULL,
  `idExpenses` INT NULL,
  `Payment` DECIMAL NULL,
  `idPayments` INT NULL,
  `Receipts` DECIMAL NULL,
  `idReceipts` INT NULL,
  PRIMARY KEY (`idCash_register`),
  INDEX `idPagamento_idx` (`idPayments` ASC),
  INDEX `idRecebimento_idx` (`idReceipts` ASC),
  INDEX `idExpenses_idx` (`idExpenses` ASC),
  CONSTRAINT `idPaymentsCash_register`
    FOREIGN KEY (`idPayments`)
    REFERENCES `simplestore`.`Payments` (`idPayments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idReceiptsCash_register`
    FOREIGN KEY (`idReceipts`)
    REFERENCES `simplestore`.`Receipts` (`idReceipts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idExpenses`
    FOREIGN KEY (`idExpenses`)
    REFERENCES `simplestore`.`Expenses` (`idExpenses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `simplestore`;

DELIMITER $$

USE `simplestore`$$
DROP TRIGGER IF EXISTS `simplestore`.`Sales_BEFORE_INSERT` $$
USE `simplestore`$$
CREATE DEFINER = CURRENT_USER TRIGGER `simplestore`.`Sales_BEFORE_INSERT` BEFORE INSERT ON `Sales` FOR EACH ROW
BEGIN
  IF (NEW.idProducts IS NULL AND NEW.idServices IS NULL) THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = '\'idProducts\' and \'idServices\' cannot both be null';
  END IF;
END$$


USE `simplestore`$$
DROP TRIGGER IF EXISTS `simplestore`.`Sales_BEFORE_UPDATE` $$
USE `simplestore`$$
CREATE DEFINER = CURRENT_USER TRIGGER `simplestore`.`Sales_BEFORE_UPDATE` BEFORE UPDATE ON `Sales` FOR EACH ROW
BEGIN
  IF (NEW.idProducts IS NULL AND NEW.idServices IS NULL) THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = '\'idProducts\' and \'idServices\' cannot both be null';
  END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
